export const HEADER_REQUEST = 'HEADER_REQUEST';
export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_GET_INFORMATION_REQUEST = 'USER_GET_INFORMATION_REQUEST';

export const DATA_COMPANY_REQUEST = 'DATA_COMPANY_REQUEST';

